/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api;

import com.vapi.api.core.ClientOptions;
import com.vapi.api.core.Environment;
import okhttp3.OkHttpClient;

public final class AsyncVapiBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private String token = null;

    private Environment environment = Environment.DEFAULT;

    /**
     * Sets token
     */
    public AsyncVapiBuilder token(String token) {
        this.token = token;
        return this;
    }

    public AsyncVapiBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }

    public AsyncVapiBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    /**
     * Sets the timeout (in seconds) for the client. Defaults to 60 seconds.
     */
    public AsyncVapiBuilder timeout(int timeout) {
        this.clientOptionsBuilder.timeout(timeout);
        return this;
    }

    /**
     * Sets the maximum number of retries for the client. Defaults to 2 retries.
     */
    public AsyncVapiBuilder maxRetries(int maxRetries) {
        this.clientOptionsBuilder.maxRetries(maxRetries);
        return this;
    }

    /**
     * Sets the underlying OkHttp client
     */
    public AsyncVapiBuilder httpClient(OkHttpClient httpClient) {
        this.clientOptionsBuilder.httpClient(httpClient);
        return this;
    }

    public AsyncVapi build() {
        if (token == null) {
            throw new RuntimeException("Please provide token");
        }
        this.clientOptionsBuilder.addHeader("Authorization", "Bearer " + this.token);
        clientOptionsBuilder.environment(this.environment);
        return new AsyncVapi(clientOptionsBuilder.build());
    }
}
