/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api;

import com.vapi.api.core.ClientOptions;
import com.vapi.api.core.Environment;

public final class VapiBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private String token = null;

    private Environment environment = Environment.DEFAULT;

    /**
     * Sets token
     */
    public VapiBuilder token(String token) {
        this.token = token;
        return this;
    }

    public VapiBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }

    public VapiBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    /**
     * Sets the timeout (in seconds) for the client
     */
    public VapiBuilder timeout(int timeout) {
        this.clientOptionsBuilder.timeout(timeout);
        return this;
    }

    public Vapi build() {
        this.clientOptionsBuilder.addHeader("Authorization", "Bearer " + this.token);
        clientOptionsBuilder.environment(this.environment);
        return new Vapi(clientOptionsBuilder.build());
    }
}
