/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.resources.workflow.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vapi.api.types.CreateAnthropicCredentialDto;
import com.vapi.api.types.CreateAnyscaleCredentialDto;
import com.vapi.api.types.CreateAssemblyAiCredentialDto;
import com.vapi.api.types.CreateAzureCredentialDto;
import com.vapi.api.types.CreateAzureOpenAiCredentialDto;
import com.vapi.api.types.CreateByoSipTrunkCredentialDto;
import com.vapi.api.types.CreateCartesiaCredentialDto;
import com.vapi.api.types.CreateCerebrasCredentialDto;
import com.vapi.api.types.CreateCloudflareCredentialDto;
import com.vapi.api.types.CreateCustomLlmCredentialDto;
import com.vapi.api.types.CreateDeepInfraCredentialDto;
import com.vapi.api.types.CreateDeepSeekCredentialDto;
import com.vapi.api.types.CreateDeepgramCredentialDto;
import com.vapi.api.types.CreateElevenLabsCredentialDto;
import com.vapi.api.types.CreateGcpCredentialDto;
import com.vapi.api.types.CreateGladiaCredentialDto;
import com.vapi.api.types.CreateGoHighLevelCredentialDto;
import com.vapi.api.types.CreateGoHighLevelMcpCredentialDto;
import com.vapi.api.types.CreateGoogleCalendarOAuth2AuthorizationCredentialDto;
import com.vapi.api.types.CreateGoogleCalendarOAuth2ClientCredentialDto;
import com.vapi.api.types.CreateGoogleCredentialDto;
import com.vapi.api.types.CreateGoogleSheetsOAuth2AuthorizationCredentialDto;
import com.vapi.api.types.CreateGroqCredentialDto;
import com.vapi.api.types.CreateHumeCredentialDto;
import com.vapi.api.types.CreateInflectionAiCredentialDto;
import com.vapi.api.types.CreateLangfuseCredentialDto;
import com.vapi.api.types.CreateLmntCredentialDto;
import com.vapi.api.types.CreateMakeCredentialDto;
import com.vapi.api.types.CreateMistralCredentialDto;
import com.vapi.api.types.CreateNeuphonicCredentialDto;
import com.vapi.api.types.CreateOpenAiCredentialDto;
import com.vapi.api.types.CreateOpenRouterCredentialDto;
import com.vapi.api.types.CreatePerplexityAiCredentialDto;
import com.vapi.api.types.CreatePlayHtCredentialDto;
import com.vapi.api.types.CreateRimeAiCredentialDto;
import com.vapi.api.types.CreateRunpodCredentialDto;
import com.vapi.api.types.CreateS3CredentialDto;
import com.vapi.api.types.CreateSlackOAuth2AuthorizationCredentialDto;
import com.vapi.api.types.CreateSmallestAiCredentialDto;
import com.vapi.api.types.CreateSpeechmaticsCredentialDto;
import com.vapi.api.types.CreateSupabaseCredentialDto;
import com.vapi.api.types.CreateTavusCredentialDto;
import com.vapi.api.types.CreateTogetherAiCredentialDto;
import com.vapi.api.types.CreateTrieveCredentialDto;
import com.vapi.api.types.CreateTwilioCredentialDto;
import com.vapi.api.types.CreateVonageCredentialDto;
import com.vapi.api.types.CreateWebhookCredentialDto;
import com.vapi.api.types.CreateXAiCredentialDto;
import java.util.Objects;
import java.util.Optional;

public final class UpdateWorkflowDtoCredentialsItem {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private UpdateWorkflowDtoCredentialsItem(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static UpdateWorkflowDtoCredentialsItem _11Labs(CreateElevenLabsCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new _11LabsValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem anthropic(CreateAnthropicCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new AnthropicValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem anyscale(CreateAnyscaleCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new AnyscaleValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem assemblyAi(CreateAssemblyAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new AssemblyAiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem azureOpenai(CreateAzureOpenAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new AzureOpenaiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem azure(CreateAzureCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new AzureValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem byoSipTrunk(CreateByoSipTrunkCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new ByoSipTrunkValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem cartesia(CreateCartesiaCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new CartesiaValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem cerebras(CreateCerebrasCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new CerebrasValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem cloudflare(CreateCloudflareCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new CloudflareValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem customLlm(CreateCustomLlmCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new CustomLlmValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem deepgram(CreateDeepgramCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new DeepgramValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem deepinfra(CreateDeepInfraCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new DeepinfraValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem deepSeek(CreateDeepSeekCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new DeepSeekValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem gcp(CreateGcpCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GcpValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem gladia(CreateGladiaCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GladiaValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem gohighlevel(CreateGoHighLevelCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GohighlevelValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem google(CreateGoogleCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GoogleValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem groq(CreateGroqCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GroqValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem inflectionAi(CreateInflectionAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new InflectionAiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem langfuse(CreateLangfuseCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new LangfuseValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem lmnt(CreateLmntCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new LmntValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem make(CreateMakeCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new MakeValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem openai(CreateOpenAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new OpenaiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem openrouter(CreateOpenRouterCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new OpenrouterValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem perplexityAi(CreatePerplexityAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new PerplexityAiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem playht(CreatePlayHtCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new PlayhtValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem rimeAi(CreateRimeAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new RimeAiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem runpod(CreateRunpodCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new RunpodValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem s3(CreateS3CredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new S3Value(value));
    }

    public static UpdateWorkflowDtoCredentialsItem supabase(CreateSupabaseCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new SupabaseValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem smallestAi(CreateSmallestAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new SmallestAiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem tavus(CreateTavusCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new TavusValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem togetherAi(CreateTogetherAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new TogetherAiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem twilio(CreateTwilioCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new TwilioValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem vonage(CreateVonageCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new VonageValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem webhook(CreateWebhookCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new WebhookValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem xai(CreateXAiCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new XaiValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem neuphonic(CreateNeuphonicCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new NeuphonicValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem hume(CreateHumeCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new HumeValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem mistral(CreateMistralCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new MistralValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem speechmatics(CreateSpeechmaticsCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new SpeechmaticsValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem trieve(CreateTrieveCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new TrieveValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem googleCalendarOauth2Client(
            CreateGoogleCalendarOAuth2ClientCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GoogleCalendarOauth2ClientValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem googleCalendarOauth2Authorization(
            CreateGoogleCalendarOAuth2AuthorizationCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GoogleCalendarOauth2AuthorizationValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem googleSheetsOauth2Authorization(
            CreateGoogleSheetsOAuth2AuthorizationCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GoogleSheetsOauth2AuthorizationValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem slackOauth2Authorization(
            CreateSlackOAuth2AuthorizationCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new SlackOauth2AuthorizationValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem ghlOauth2Authorization(CreateGoHighLevelMcpCredentialDto value) {
        return new UpdateWorkflowDtoCredentialsItem(new GhlOauth2AuthorizationValue(value));
    }

    public static UpdateWorkflowDtoCredentialsItem inworld(Object value) {
        return new UpdateWorkflowDtoCredentialsItem(new InworldValue(value));
    }

    public boolean is11Labs() {
        return value instanceof _11LabsValue;
    }

    public boolean isAnthropic() {
        return value instanceof AnthropicValue;
    }

    public boolean isAnyscale() {
        return value instanceof AnyscaleValue;
    }

    public boolean isAssemblyAi() {
        return value instanceof AssemblyAiValue;
    }

    public boolean isAzureOpenai() {
        return value instanceof AzureOpenaiValue;
    }

    public boolean isAzure() {
        return value instanceof AzureValue;
    }

    public boolean isByoSipTrunk() {
        return value instanceof ByoSipTrunkValue;
    }

    public boolean isCartesia() {
        return value instanceof CartesiaValue;
    }

    public boolean isCerebras() {
        return value instanceof CerebrasValue;
    }

    public boolean isCloudflare() {
        return value instanceof CloudflareValue;
    }

    public boolean isCustomLlm() {
        return value instanceof CustomLlmValue;
    }

    public boolean isDeepgram() {
        return value instanceof DeepgramValue;
    }

    public boolean isDeepinfra() {
        return value instanceof DeepinfraValue;
    }

    public boolean isDeepSeek() {
        return value instanceof DeepSeekValue;
    }

    public boolean isGcp() {
        return value instanceof GcpValue;
    }

    public boolean isGladia() {
        return value instanceof GladiaValue;
    }

    public boolean isGohighlevel() {
        return value instanceof GohighlevelValue;
    }

    public boolean isGoogle() {
        return value instanceof GoogleValue;
    }

    public boolean isGroq() {
        return value instanceof GroqValue;
    }

    public boolean isInflectionAi() {
        return value instanceof InflectionAiValue;
    }

    public boolean isLangfuse() {
        return value instanceof LangfuseValue;
    }

    public boolean isLmnt() {
        return value instanceof LmntValue;
    }

    public boolean isMake() {
        return value instanceof MakeValue;
    }

    public boolean isOpenai() {
        return value instanceof OpenaiValue;
    }

    public boolean isOpenrouter() {
        return value instanceof OpenrouterValue;
    }

    public boolean isPerplexityAi() {
        return value instanceof PerplexityAiValue;
    }

    public boolean isPlayht() {
        return value instanceof PlayhtValue;
    }

    public boolean isRimeAi() {
        return value instanceof RimeAiValue;
    }

    public boolean isRunpod() {
        return value instanceof RunpodValue;
    }

    public boolean isS3() {
        return value instanceof S3Value;
    }

    public boolean isSupabase() {
        return value instanceof SupabaseValue;
    }

    public boolean isSmallestAi() {
        return value instanceof SmallestAiValue;
    }

    public boolean isTavus() {
        return value instanceof TavusValue;
    }

    public boolean isTogetherAi() {
        return value instanceof TogetherAiValue;
    }

    public boolean isTwilio() {
        return value instanceof TwilioValue;
    }

    public boolean isVonage() {
        return value instanceof VonageValue;
    }

    public boolean isWebhook() {
        return value instanceof WebhookValue;
    }

    public boolean isXai() {
        return value instanceof XaiValue;
    }

    public boolean isNeuphonic() {
        return value instanceof NeuphonicValue;
    }

    public boolean isHume() {
        return value instanceof HumeValue;
    }

    public boolean isMistral() {
        return value instanceof MistralValue;
    }

    public boolean isSpeechmatics() {
        return value instanceof SpeechmaticsValue;
    }

    public boolean isTrieve() {
        return value instanceof TrieveValue;
    }

    public boolean isGoogleCalendarOauth2Client() {
        return value instanceof GoogleCalendarOauth2ClientValue;
    }

    public boolean isGoogleCalendarOauth2Authorization() {
        return value instanceof GoogleCalendarOauth2AuthorizationValue;
    }

    public boolean isGoogleSheetsOauth2Authorization() {
        return value instanceof GoogleSheetsOauth2AuthorizationValue;
    }

    public boolean isSlackOauth2Authorization() {
        return value instanceof SlackOauth2AuthorizationValue;
    }

    public boolean isGhlOauth2Authorization() {
        return value instanceof GhlOauth2AuthorizationValue;
    }

    public boolean isInworld() {
        return value instanceof InworldValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<CreateElevenLabsCredentialDto> get11Labs() {
        if (is11Labs()) {
            return Optional.of(((_11LabsValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateAnthropicCredentialDto> getAnthropic() {
        if (isAnthropic()) {
            return Optional.of(((AnthropicValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateAnyscaleCredentialDto> getAnyscale() {
        if (isAnyscale()) {
            return Optional.of(((AnyscaleValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateAssemblyAiCredentialDto> getAssemblyAi() {
        if (isAssemblyAi()) {
            return Optional.of(((AssemblyAiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateAzureOpenAiCredentialDto> getAzureOpenai() {
        if (isAzureOpenai()) {
            return Optional.of(((AzureOpenaiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateAzureCredentialDto> getAzure() {
        if (isAzure()) {
            return Optional.of(((AzureValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateByoSipTrunkCredentialDto> getByoSipTrunk() {
        if (isByoSipTrunk()) {
            return Optional.of(((ByoSipTrunkValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateCartesiaCredentialDto> getCartesia() {
        if (isCartesia()) {
            return Optional.of(((CartesiaValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateCerebrasCredentialDto> getCerebras() {
        if (isCerebras()) {
            return Optional.of(((CerebrasValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateCloudflareCredentialDto> getCloudflare() {
        if (isCloudflare()) {
            return Optional.of(((CloudflareValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateCustomLlmCredentialDto> getCustomLlm() {
        if (isCustomLlm()) {
            return Optional.of(((CustomLlmValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateDeepgramCredentialDto> getDeepgram() {
        if (isDeepgram()) {
            return Optional.of(((DeepgramValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateDeepInfraCredentialDto> getDeepinfra() {
        if (isDeepinfra()) {
            return Optional.of(((DeepinfraValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateDeepSeekCredentialDto> getDeepSeek() {
        if (isDeepSeek()) {
            return Optional.of(((DeepSeekValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGcpCredentialDto> getGcp() {
        if (isGcp()) {
            return Optional.of(((GcpValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGladiaCredentialDto> getGladia() {
        if (isGladia()) {
            return Optional.of(((GladiaValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGoHighLevelCredentialDto> getGohighlevel() {
        if (isGohighlevel()) {
            return Optional.of(((GohighlevelValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGoogleCredentialDto> getGoogle() {
        if (isGoogle()) {
            return Optional.of(((GoogleValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGroqCredentialDto> getGroq() {
        if (isGroq()) {
            return Optional.of(((GroqValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateInflectionAiCredentialDto> getInflectionAi() {
        if (isInflectionAi()) {
            return Optional.of(((InflectionAiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateLangfuseCredentialDto> getLangfuse() {
        if (isLangfuse()) {
            return Optional.of(((LangfuseValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateLmntCredentialDto> getLmnt() {
        if (isLmnt()) {
            return Optional.of(((LmntValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateMakeCredentialDto> getMake() {
        if (isMake()) {
            return Optional.of(((MakeValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateOpenAiCredentialDto> getOpenai() {
        if (isOpenai()) {
            return Optional.of(((OpenaiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateOpenRouterCredentialDto> getOpenrouter() {
        if (isOpenrouter()) {
            return Optional.of(((OpenrouterValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreatePerplexityAiCredentialDto> getPerplexityAi() {
        if (isPerplexityAi()) {
            return Optional.of(((PerplexityAiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreatePlayHtCredentialDto> getPlayht() {
        if (isPlayht()) {
            return Optional.of(((PlayhtValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateRimeAiCredentialDto> getRimeAi() {
        if (isRimeAi()) {
            return Optional.of(((RimeAiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateRunpodCredentialDto> getRunpod() {
        if (isRunpod()) {
            return Optional.of(((RunpodValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateS3CredentialDto> getS3() {
        if (isS3()) {
            return Optional.of(((S3Value) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateSupabaseCredentialDto> getSupabase() {
        if (isSupabase()) {
            return Optional.of(((SupabaseValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateSmallestAiCredentialDto> getSmallestAi() {
        if (isSmallestAi()) {
            return Optional.of(((SmallestAiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateTavusCredentialDto> getTavus() {
        if (isTavus()) {
            return Optional.of(((TavusValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateTogetherAiCredentialDto> getTogetherAi() {
        if (isTogetherAi()) {
            return Optional.of(((TogetherAiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateTwilioCredentialDto> getTwilio() {
        if (isTwilio()) {
            return Optional.of(((TwilioValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateVonageCredentialDto> getVonage() {
        if (isVonage()) {
            return Optional.of(((VonageValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateWebhookCredentialDto> getWebhook() {
        if (isWebhook()) {
            return Optional.of(((WebhookValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateXAiCredentialDto> getXai() {
        if (isXai()) {
            return Optional.of(((XaiValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateNeuphonicCredentialDto> getNeuphonic() {
        if (isNeuphonic()) {
            return Optional.of(((NeuphonicValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateHumeCredentialDto> getHume() {
        if (isHume()) {
            return Optional.of(((HumeValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateMistralCredentialDto> getMistral() {
        if (isMistral()) {
            return Optional.of(((MistralValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateSpeechmaticsCredentialDto> getSpeechmatics() {
        if (isSpeechmatics()) {
            return Optional.of(((SpeechmaticsValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateTrieveCredentialDto> getTrieve() {
        if (isTrieve()) {
            return Optional.of(((TrieveValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGoogleCalendarOAuth2ClientCredentialDto> getGoogleCalendarOauth2Client() {
        if (isGoogleCalendarOauth2Client()) {
            return Optional.of(((GoogleCalendarOauth2ClientValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGoogleCalendarOAuth2AuthorizationCredentialDto> getGoogleCalendarOauth2Authorization() {
        if (isGoogleCalendarOauth2Authorization()) {
            return Optional.of(((GoogleCalendarOauth2AuthorizationValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGoogleSheetsOAuth2AuthorizationCredentialDto> getGoogleSheetsOauth2Authorization() {
        if (isGoogleSheetsOauth2Authorization()) {
            return Optional.of(((GoogleSheetsOauth2AuthorizationValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateSlackOAuth2AuthorizationCredentialDto> getSlackOauth2Authorization() {
        if (isSlackOauth2Authorization()) {
            return Optional.of(((SlackOauth2AuthorizationValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateGoHighLevelMcpCredentialDto> getGhlOauth2Authorization() {
        if (isGhlOauth2Authorization()) {
            return Optional.of(((GhlOauth2AuthorizationValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> getInworld() {
        if (isInworld()) {
            return Optional.of(((InworldValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visit11Labs(CreateElevenLabsCredentialDto _11Labs);

        T visitAnthropic(CreateAnthropicCredentialDto anthropic);

        T visitAnyscale(CreateAnyscaleCredentialDto anyscale);

        T visitAssemblyAi(CreateAssemblyAiCredentialDto assemblyAi);

        T visitAzureOpenai(CreateAzureOpenAiCredentialDto azureOpenai);

        T visitAzure(CreateAzureCredentialDto azure);

        T visitByoSipTrunk(CreateByoSipTrunkCredentialDto byoSipTrunk);

        T visitCartesia(CreateCartesiaCredentialDto cartesia);

        T visitCerebras(CreateCerebrasCredentialDto cerebras);

        T visitCloudflare(CreateCloudflareCredentialDto cloudflare);

        T visitCustomLlm(CreateCustomLlmCredentialDto customLlm);

        T visitDeepgram(CreateDeepgramCredentialDto deepgram);

        T visitDeepinfra(CreateDeepInfraCredentialDto deepinfra);

        T visitDeepSeek(CreateDeepSeekCredentialDto deepSeek);

        T visitGcp(CreateGcpCredentialDto gcp);

        T visitGladia(CreateGladiaCredentialDto gladia);

        T visitGohighlevel(CreateGoHighLevelCredentialDto gohighlevel);

        T visitGoogle(CreateGoogleCredentialDto google);

        T visitGroq(CreateGroqCredentialDto groq);

        T visitInflectionAi(CreateInflectionAiCredentialDto inflectionAi);

        T visitLangfuse(CreateLangfuseCredentialDto langfuse);

        T visitLmnt(CreateLmntCredentialDto lmnt);

        T visitMake(CreateMakeCredentialDto make);

        T visitOpenai(CreateOpenAiCredentialDto openai);

        T visitOpenrouter(CreateOpenRouterCredentialDto openrouter);

        T visitPerplexityAi(CreatePerplexityAiCredentialDto perplexityAi);

        T visitPlayht(CreatePlayHtCredentialDto playht);

        T visitRimeAi(CreateRimeAiCredentialDto rimeAi);

        T visitRunpod(CreateRunpodCredentialDto runpod);

        T visitS3(CreateS3CredentialDto s3);

        T visitSupabase(CreateSupabaseCredentialDto supabase);

        T visitSmallestAi(CreateSmallestAiCredentialDto smallestAi);

        T visitTavus(CreateTavusCredentialDto tavus);

        T visitTogetherAi(CreateTogetherAiCredentialDto togetherAi);

        T visitTwilio(CreateTwilioCredentialDto twilio);

        T visitVonage(CreateVonageCredentialDto vonage);

        T visitWebhook(CreateWebhookCredentialDto webhook);

        T visitXai(CreateXAiCredentialDto xai);

        T visitNeuphonic(CreateNeuphonicCredentialDto neuphonic);

        T visitHume(CreateHumeCredentialDto hume);

        T visitMistral(CreateMistralCredentialDto mistral);

        T visitSpeechmatics(CreateSpeechmaticsCredentialDto speechmatics);

        T visitTrieve(CreateTrieveCredentialDto trieve);

        T visitGoogleCalendarOauth2Client(CreateGoogleCalendarOAuth2ClientCredentialDto googleCalendarOauth2Client);

        T visitGoogleCalendarOauth2Authorization(
                CreateGoogleCalendarOAuth2AuthorizationCredentialDto googleCalendarOauth2Authorization);

        T visitGoogleSheetsOauth2Authorization(
                CreateGoogleSheetsOAuth2AuthorizationCredentialDto googleSheetsOauth2Authorization);

        T visitSlackOauth2Authorization(CreateSlackOAuth2AuthorizationCredentialDto slackOauth2Authorization);

        T visitGhlOauth2Authorization(CreateGoHighLevelMcpCredentialDto ghlOauth2Authorization);

        T visitInworld(Object inworld);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "provider", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({
        @JsonSubTypes.Type(_11LabsValue.class),
        @JsonSubTypes.Type(AnthropicValue.class),
        @JsonSubTypes.Type(AnyscaleValue.class),
        @JsonSubTypes.Type(AssemblyAiValue.class),
        @JsonSubTypes.Type(AzureOpenaiValue.class),
        @JsonSubTypes.Type(AzureValue.class),
        @JsonSubTypes.Type(ByoSipTrunkValue.class),
        @JsonSubTypes.Type(CartesiaValue.class),
        @JsonSubTypes.Type(CerebrasValue.class),
        @JsonSubTypes.Type(CloudflareValue.class),
        @JsonSubTypes.Type(CustomLlmValue.class),
        @JsonSubTypes.Type(DeepgramValue.class),
        @JsonSubTypes.Type(DeepinfraValue.class),
        @JsonSubTypes.Type(DeepSeekValue.class),
        @JsonSubTypes.Type(GcpValue.class),
        @JsonSubTypes.Type(GladiaValue.class),
        @JsonSubTypes.Type(GohighlevelValue.class),
        @JsonSubTypes.Type(GoogleValue.class),
        @JsonSubTypes.Type(GroqValue.class),
        @JsonSubTypes.Type(InflectionAiValue.class),
        @JsonSubTypes.Type(LangfuseValue.class),
        @JsonSubTypes.Type(LmntValue.class),
        @JsonSubTypes.Type(MakeValue.class),
        @JsonSubTypes.Type(OpenaiValue.class),
        @JsonSubTypes.Type(OpenrouterValue.class),
        @JsonSubTypes.Type(PerplexityAiValue.class),
        @JsonSubTypes.Type(PlayhtValue.class),
        @JsonSubTypes.Type(RimeAiValue.class),
        @JsonSubTypes.Type(RunpodValue.class),
        @JsonSubTypes.Type(S3Value.class),
        @JsonSubTypes.Type(SupabaseValue.class),
        @JsonSubTypes.Type(SmallestAiValue.class),
        @JsonSubTypes.Type(TavusValue.class),
        @JsonSubTypes.Type(TogetherAiValue.class),
        @JsonSubTypes.Type(TwilioValue.class),
        @JsonSubTypes.Type(VonageValue.class),
        @JsonSubTypes.Type(WebhookValue.class),
        @JsonSubTypes.Type(XaiValue.class),
        @JsonSubTypes.Type(NeuphonicValue.class),
        @JsonSubTypes.Type(HumeValue.class),
        @JsonSubTypes.Type(MistralValue.class),
        @JsonSubTypes.Type(SpeechmaticsValue.class),
        @JsonSubTypes.Type(TrieveValue.class),
        @JsonSubTypes.Type(GoogleCalendarOauth2ClientValue.class),
        @JsonSubTypes.Type(GoogleCalendarOauth2AuthorizationValue.class),
        @JsonSubTypes.Type(GoogleSheetsOauth2AuthorizationValue.class),
        @JsonSubTypes.Type(SlackOauth2AuthorizationValue.class),
        @JsonSubTypes.Type(GhlOauth2AuthorizationValue.class),
        @JsonSubTypes.Type(InworldValue.class)
    })
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("11labs")
    @JsonIgnoreProperties("provider")
    private static final class _11LabsValue implements Value {
        @JsonUnwrapped
        private CreateElevenLabsCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _11LabsValue() {}

        private _11LabsValue(CreateElevenLabsCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visit11Labs(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _11LabsValue && equalTo((_11LabsValue) other);
        }

        private boolean equalTo(_11LabsValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("anthropic")
    @JsonIgnoreProperties("provider")
    private static final class AnthropicValue implements Value {
        @JsonUnwrapped
        private CreateAnthropicCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AnthropicValue() {}

        private AnthropicValue(CreateAnthropicCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAnthropic(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AnthropicValue && equalTo((AnthropicValue) other);
        }

        private boolean equalTo(AnthropicValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("anyscale")
    @JsonIgnoreProperties("provider")
    private static final class AnyscaleValue implements Value {
        @JsonUnwrapped
        private CreateAnyscaleCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AnyscaleValue() {}

        private AnyscaleValue(CreateAnyscaleCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAnyscale(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AnyscaleValue && equalTo((AnyscaleValue) other);
        }

        private boolean equalTo(AnyscaleValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("assembly-ai")
    @JsonIgnoreProperties("provider")
    private static final class AssemblyAiValue implements Value {
        @JsonUnwrapped
        private CreateAssemblyAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AssemblyAiValue() {}

        private AssemblyAiValue(CreateAssemblyAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAssemblyAi(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AssemblyAiValue && equalTo((AssemblyAiValue) other);
        }

        private boolean equalTo(AssemblyAiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("azure-openai")
    @JsonIgnoreProperties("provider")
    private static final class AzureOpenaiValue implements Value {
        @JsonUnwrapped
        private CreateAzureOpenAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AzureOpenaiValue() {}

        private AzureOpenaiValue(CreateAzureOpenAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAzureOpenai(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AzureOpenaiValue && equalTo((AzureOpenaiValue) other);
        }

        private boolean equalTo(AzureOpenaiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("azure")
    @JsonIgnoreProperties("provider")
    private static final class AzureValue implements Value {
        @JsonUnwrapped
        private CreateAzureCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AzureValue() {}

        private AzureValue(CreateAzureCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAzure(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AzureValue && equalTo((AzureValue) other);
        }

        private boolean equalTo(AzureValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("byo-sip-trunk")
    @JsonIgnoreProperties("provider")
    private static final class ByoSipTrunkValue implements Value {
        @JsonUnwrapped
        private CreateByoSipTrunkCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private ByoSipTrunkValue() {}

        private ByoSipTrunkValue(CreateByoSipTrunkCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitByoSipTrunk(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ByoSipTrunkValue && equalTo((ByoSipTrunkValue) other);
        }

        private boolean equalTo(ByoSipTrunkValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("cartesia")
    @JsonIgnoreProperties("provider")
    private static final class CartesiaValue implements Value {
        @JsonUnwrapped
        private CreateCartesiaCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private CartesiaValue() {}

        private CartesiaValue(CreateCartesiaCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitCartesia(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof CartesiaValue && equalTo((CartesiaValue) other);
        }

        private boolean equalTo(CartesiaValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("cerebras")
    @JsonIgnoreProperties("provider")
    private static final class CerebrasValue implements Value {
        @JsonUnwrapped
        private CreateCerebrasCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private CerebrasValue() {}

        private CerebrasValue(CreateCerebrasCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitCerebras(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof CerebrasValue && equalTo((CerebrasValue) other);
        }

        private boolean equalTo(CerebrasValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("cloudflare")
    @JsonIgnoreProperties("provider")
    private static final class CloudflareValue implements Value {
        @JsonUnwrapped
        private CreateCloudflareCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private CloudflareValue() {}

        private CloudflareValue(CreateCloudflareCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitCloudflare(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof CloudflareValue && equalTo((CloudflareValue) other);
        }

        private boolean equalTo(CloudflareValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("custom-llm")
    @JsonIgnoreProperties("provider")
    private static final class CustomLlmValue implements Value {
        @JsonUnwrapped
        private CreateCustomLlmCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private CustomLlmValue() {}

        private CustomLlmValue(CreateCustomLlmCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitCustomLlm(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof CustomLlmValue && equalTo((CustomLlmValue) other);
        }

        private boolean equalTo(CustomLlmValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("deepgram")
    @JsonIgnoreProperties("provider")
    private static final class DeepgramValue implements Value {
        @JsonUnwrapped
        private CreateDeepgramCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private DeepgramValue() {}

        private DeepgramValue(CreateDeepgramCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitDeepgram(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof DeepgramValue && equalTo((DeepgramValue) other);
        }

        private boolean equalTo(DeepgramValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("deepinfra")
    @JsonIgnoreProperties("provider")
    private static final class DeepinfraValue implements Value {
        @JsonUnwrapped
        private CreateDeepInfraCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private DeepinfraValue() {}

        private DeepinfraValue(CreateDeepInfraCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitDeepinfra(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof DeepinfraValue && equalTo((DeepinfraValue) other);
        }

        private boolean equalTo(DeepinfraValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("deep-seek")
    @JsonIgnoreProperties("provider")
    private static final class DeepSeekValue implements Value {
        @JsonUnwrapped
        private CreateDeepSeekCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private DeepSeekValue() {}

        private DeepSeekValue(CreateDeepSeekCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitDeepSeek(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof DeepSeekValue && equalTo((DeepSeekValue) other);
        }

        private boolean equalTo(DeepSeekValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("gcp")
    @JsonIgnoreProperties("provider")
    private static final class GcpValue implements Value {
        @JsonUnwrapped
        private CreateGcpCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GcpValue() {}

        private GcpValue(CreateGcpCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGcp(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GcpValue && equalTo((GcpValue) other);
        }

        private boolean equalTo(GcpValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("gladia")
    @JsonIgnoreProperties("provider")
    private static final class GladiaValue implements Value {
        @JsonUnwrapped
        private CreateGladiaCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GladiaValue() {}

        private GladiaValue(CreateGladiaCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGladia(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GladiaValue && equalTo((GladiaValue) other);
        }

        private boolean equalTo(GladiaValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("gohighlevel")
    @JsonIgnoreProperties("provider")
    private static final class GohighlevelValue implements Value {
        @JsonUnwrapped
        private CreateGoHighLevelCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GohighlevelValue() {}

        private GohighlevelValue(CreateGoHighLevelCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGohighlevel(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GohighlevelValue && equalTo((GohighlevelValue) other);
        }

        private boolean equalTo(GohighlevelValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("google")
    @JsonIgnoreProperties("provider")
    private static final class GoogleValue implements Value {
        @JsonUnwrapped
        private CreateGoogleCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GoogleValue() {}

        private GoogleValue(CreateGoogleCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGoogle(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GoogleValue && equalTo((GoogleValue) other);
        }

        private boolean equalTo(GoogleValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("groq")
    @JsonIgnoreProperties("provider")
    private static final class GroqValue implements Value {
        @JsonUnwrapped
        private CreateGroqCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GroqValue() {}

        private GroqValue(CreateGroqCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGroq(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GroqValue && equalTo((GroqValue) other);
        }

        private boolean equalTo(GroqValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("inflection-ai")
    @JsonIgnoreProperties("provider")
    private static final class InflectionAiValue implements Value {
        @JsonUnwrapped
        private CreateInflectionAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private InflectionAiValue() {}

        private InflectionAiValue(CreateInflectionAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitInflectionAi(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof InflectionAiValue && equalTo((InflectionAiValue) other);
        }

        private boolean equalTo(InflectionAiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("langfuse")
    @JsonIgnoreProperties("provider")
    private static final class LangfuseValue implements Value {
        @JsonUnwrapped
        private CreateLangfuseCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private LangfuseValue() {}

        private LangfuseValue(CreateLangfuseCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitLangfuse(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof LangfuseValue && equalTo((LangfuseValue) other);
        }

        private boolean equalTo(LangfuseValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("lmnt")
    @JsonIgnoreProperties("provider")
    private static final class LmntValue implements Value {
        @JsonUnwrapped
        private CreateLmntCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private LmntValue() {}

        private LmntValue(CreateLmntCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitLmnt(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof LmntValue && equalTo((LmntValue) other);
        }

        private boolean equalTo(LmntValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("make")
    @JsonIgnoreProperties("provider")
    private static final class MakeValue implements Value {
        @JsonUnwrapped
        private CreateMakeCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private MakeValue() {}

        private MakeValue(CreateMakeCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitMake(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof MakeValue && equalTo((MakeValue) other);
        }

        private boolean equalTo(MakeValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("openai")
    @JsonIgnoreProperties("provider")
    private static final class OpenaiValue implements Value {
        @JsonUnwrapped
        private CreateOpenAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private OpenaiValue() {}

        private OpenaiValue(CreateOpenAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitOpenai(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof OpenaiValue && equalTo((OpenaiValue) other);
        }

        private boolean equalTo(OpenaiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("openrouter")
    @JsonIgnoreProperties("provider")
    private static final class OpenrouterValue implements Value {
        @JsonUnwrapped
        private CreateOpenRouterCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private OpenrouterValue() {}

        private OpenrouterValue(CreateOpenRouterCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitOpenrouter(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof OpenrouterValue && equalTo((OpenrouterValue) other);
        }

        private boolean equalTo(OpenrouterValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("perplexity-ai")
    @JsonIgnoreProperties("provider")
    private static final class PerplexityAiValue implements Value {
        @JsonUnwrapped
        private CreatePerplexityAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PerplexityAiValue() {}

        private PerplexityAiValue(CreatePerplexityAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPerplexityAi(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PerplexityAiValue && equalTo((PerplexityAiValue) other);
        }

        private boolean equalTo(PerplexityAiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("playht")
    @JsonIgnoreProperties("provider")
    private static final class PlayhtValue implements Value {
        @JsonUnwrapped
        private CreatePlayHtCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PlayhtValue() {}

        private PlayhtValue(CreatePlayHtCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPlayht(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PlayhtValue && equalTo((PlayhtValue) other);
        }

        private boolean equalTo(PlayhtValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("rime-ai")
    @JsonIgnoreProperties("provider")
    private static final class RimeAiValue implements Value {
        @JsonUnwrapped
        private CreateRimeAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private RimeAiValue() {}

        private RimeAiValue(CreateRimeAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitRimeAi(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof RimeAiValue && equalTo((RimeAiValue) other);
        }

        private boolean equalTo(RimeAiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("runpod")
    @JsonIgnoreProperties("provider")
    private static final class RunpodValue implements Value {
        @JsonUnwrapped
        private CreateRunpodCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private RunpodValue() {}

        private RunpodValue(CreateRunpodCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitRunpod(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof RunpodValue && equalTo((RunpodValue) other);
        }

        private boolean equalTo(RunpodValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("s3")
    @JsonIgnoreProperties("provider")
    private static final class S3Value implements Value {
        @JsonUnwrapped
        private CreateS3CredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private S3Value() {}

        private S3Value(CreateS3CredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitS3(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof S3Value && equalTo((S3Value) other);
        }

        private boolean equalTo(S3Value other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("supabase")
    @JsonIgnoreProperties("provider")
    private static final class SupabaseValue implements Value {
        @JsonUnwrapped
        private CreateSupabaseCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private SupabaseValue() {}

        private SupabaseValue(CreateSupabaseCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitSupabase(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof SupabaseValue && equalTo((SupabaseValue) other);
        }

        private boolean equalTo(SupabaseValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("smallest-ai")
    @JsonIgnoreProperties("provider")
    private static final class SmallestAiValue implements Value {
        @JsonUnwrapped
        private CreateSmallestAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private SmallestAiValue() {}

        private SmallestAiValue(CreateSmallestAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitSmallestAi(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof SmallestAiValue && equalTo((SmallestAiValue) other);
        }

        private boolean equalTo(SmallestAiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("tavus")
    @JsonIgnoreProperties("provider")
    private static final class TavusValue implements Value {
        @JsonUnwrapped
        private CreateTavusCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private TavusValue() {}

        private TavusValue(CreateTavusCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitTavus(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TavusValue && equalTo((TavusValue) other);
        }

        private boolean equalTo(TavusValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("together-ai")
    @JsonIgnoreProperties("provider")
    private static final class TogetherAiValue implements Value {
        @JsonUnwrapped
        private CreateTogetherAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private TogetherAiValue() {}

        private TogetherAiValue(CreateTogetherAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitTogetherAi(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TogetherAiValue && equalTo((TogetherAiValue) other);
        }

        private boolean equalTo(TogetherAiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("twilio")
    @JsonIgnoreProperties("provider")
    private static final class TwilioValue implements Value {
        @JsonUnwrapped
        private CreateTwilioCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private TwilioValue() {}

        private TwilioValue(CreateTwilioCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitTwilio(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TwilioValue && equalTo((TwilioValue) other);
        }

        private boolean equalTo(TwilioValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("vonage")
    @JsonIgnoreProperties("provider")
    private static final class VonageValue implements Value {
        @JsonUnwrapped
        private CreateVonageCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private VonageValue() {}

        private VonageValue(CreateVonageCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitVonage(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof VonageValue && equalTo((VonageValue) other);
        }

        private boolean equalTo(VonageValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("webhook")
    @JsonIgnoreProperties("provider")
    private static final class WebhookValue implements Value {
        @JsonUnwrapped
        private CreateWebhookCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private WebhookValue() {}

        private WebhookValue(CreateWebhookCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitWebhook(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof WebhookValue && equalTo((WebhookValue) other);
        }

        private boolean equalTo(WebhookValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("xai")
    @JsonIgnoreProperties("provider")
    private static final class XaiValue implements Value {
        @JsonUnwrapped
        private CreateXAiCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private XaiValue() {}

        private XaiValue(CreateXAiCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitXai(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof XaiValue && equalTo((XaiValue) other);
        }

        private boolean equalTo(XaiValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("neuphonic")
    @JsonIgnoreProperties("provider")
    private static final class NeuphonicValue implements Value {
        @JsonUnwrapped
        private CreateNeuphonicCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private NeuphonicValue() {}

        private NeuphonicValue(CreateNeuphonicCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitNeuphonic(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof NeuphonicValue && equalTo((NeuphonicValue) other);
        }

        private boolean equalTo(NeuphonicValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("hume")
    @JsonIgnoreProperties("provider")
    private static final class HumeValue implements Value {
        @JsonUnwrapped
        private CreateHumeCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private HumeValue() {}

        private HumeValue(CreateHumeCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitHume(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof HumeValue && equalTo((HumeValue) other);
        }

        private boolean equalTo(HumeValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("mistral")
    @JsonIgnoreProperties("provider")
    private static final class MistralValue implements Value {
        @JsonUnwrapped
        private CreateMistralCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private MistralValue() {}

        private MistralValue(CreateMistralCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitMistral(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof MistralValue && equalTo((MistralValue) other);
        }

        private boolean equalTo(MistralValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("speechmatics")
    @JsonIgnoreProperties("provider")
    private static final class SpeechmaticsValue implements Value {
        @JsonUnwrapped
        private CreateSpeechmaticsCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private SpeechmaticsValue() {}

        private SpeechmaticsValue(CreateSpeechmaticsCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitSpeechmatics(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof SpeechmaticsValue && equalTo((SpeechmaticsValue) other);
        }

        private boolean equalTo(SpeechmaticsValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("trieve")
    @JsonIgnoreProperties("provider")
    private static final class TrieveValue implements Value {
        @JsonUnwrapped
        private CreateTrieveCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private TrieveValue() {}

        private TrieveValue(CreateTrieveCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitTrieve(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TrieveValue && equalTo((TrieveValue) other);
        }

        private boolean equalTo(TrieveValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("google.calendar.oauth2-client")
    @JsonIgnoreProperties("provider")
    private static final class GoogleCalendarOauth2ClientValue implements Value {
        @JsonUnwrapped
        private CreateGoogleCalendarOAuth2ClientCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GoogleCalendarOauth2ClientValue() {}

        private GoogleCalendarOauth2ClientValue(CreateGoogleCalendarOAuth2ClientCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGoogleCalendarOauth2Client(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GoogleCalendarOauth2ClientValue && equalTo((GoogleCalendarOauth2ClientValue) other);
        }

        private boolean equalTo(GoogleCalendarOauth2ClientValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("google.calendar.oauth2-authorization")
    @JsonIgnoreProperties("provider")
    private static final class GoogleCalendarOauth2AuthorizationValue implements Value {
        @JsonUnwrapped
        private CreateGoogleCalendarOAuth2AuthorizationCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GoogleCalendarOauth2AuthorizationValue() {}

        private GoogleCalendarOauth2AuthorizationValue(CreateGoogleCalendarOAuth2AuthorizationCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGoogleCalendarOauth2Authorization(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GoogleCalendarOauth2AuthorizationValue
                    && equalTo((GoogleCalendarOauth2AuthorizationValue) other);
        }

        private boolean equalTo(GoogleCalendarOauth2AuthorizationValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("google.sheets.oauth2-authorization")
    @JsonIgnoreProperties("provider")
    private static final class GoogleSheetsOauth2AuthorizationValue implements Value {
        @JsonUnwrapped
        private CreateGoogleSheetsOAuth2AuthorizationCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GoogleSheetsOauth2AuthorizationValue() {}

        private GoogleSheetsOauth2AuthorizationValue(CreateGoogleSheetsOAuth2AuthorizationCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGoogleSheetsOauth2Authorization(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GoogleSheetsOauth2AuthorizationValue
                    && equalTo((GoogleSheetsOauth2AuthorizationValue) other);
        }

        private boolean equalTo(GoogleSheetsOauth2AuthorizationValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("slack.oauth2-authorization")
    @JsonIgnoreProperties("provider")
    private static final class SlackOauth2AuthorizationValue implements Value {
        @JsonUnwrapped
        private CreateSlackOAuth2AuthorizationCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private SlackOauth2AuthorizationValue() {}

        private SlackOauth2AuthorizationValue(CreateSlackOAuth2AuthorizationCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitSlackOauth2Authorization(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof SlackOauth2AuthorizationValue && equalTo((SlackOauth2AuthorizationValue) other);
        }

        private boolean equalTo(SlackOauth2AuthorizationValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("ghl.oauth2-authorization")
    @JsonIgnoreProperties("provider")
    private static final class GhlOauth2AuthorizationValue implements Value {
        @JsonUnwrapped
        private CreateGoHighLevelMcpCredentialDto value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private GhlOauth2AuthorizationValue() {}

        private GhlOauth2AuthorizationValue(CreateGoHighLevelMcpCredentialDto value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitGhlOauth2Authorization(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof GhlOauth2AuthorizationValue && equalTo((GhlOauth2AuthorizationValue) other);
        }

        private boolean equalTo(GhlOauth2AuthorizationValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("inworld")
    @JsonIgnoreProperties("provider")
    private static final class InworldValue implements Value {
        @JsonProperty("value")
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private InworldValue(@JsonProperty("value") Object value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitInworld(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof InworldValue && equalTo((InworldValue) other);
        }

        private boolean equalTo(InworldValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("provider")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "UpdateWorkflowDtoCredentialsItem{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
