/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.resources.tools;

import com.vapi.api.core.ClientOptions;
import com.vapi.api.core.RequestOptions;
import com.vapi.api.resources.tools.requests.ToolsListRequest;
import com.vapi.api.resources.tools.types.ToolsCreateRequest;
import com.vapi.api.resources.tools.types.ToolsCreateResponse;
import com.vapi.api.resources.tools.types.ToolsDeleteResponse;
import com.vapi.api.resources.tools.types.ToolsGetResponse;
import com.vapi.api.resources.tools.types.ToolsListResponseItem;
import com.vapi.api.resources.tools.types.ToolsUpdateRequest;
import com.vapi.api.resources.tools.types.ToolsUpdateResponse;
import java.util.List;

public class ToolsClient {
    protected final ClientOptions clientOptions;

    private final RawToolsClient rawClient;

    public ToolsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawToolsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawToolsClient withRawResponse() {
        return this.rawClient;
    }

    public List<ToolsListResponseItem> list() {
        return this.rawClient.list().body();
    }

    public List<ToolsListResponseItem> list(ToolsListRequest request) {
        return this.rawClient.list(request).body();
    }

    public List<ToolsListResponseItem> list(ToolsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    public ToolsCreateResponse create(ToolsCreateRequest request) {
        return this.rawClient.create(request).body();
    }

    public ToolsCreateResponse create(ToolsCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    public ToolsGetResponse get(String id) {
        return this.rawClient.get(id).body();
    }

    public ToolsGetResponse get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).body();
    }

    public ToolsDeleteResponse delete(String id) {
        return this.rawClient.delete(id).body();
    }

    public ToolsDeleteResponse delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).body();
    }

    public ToolsUpdateResponse update(String id, ToolsUpdateRequest request) {
        return this.rawClient.update(id, request).body();
    }

    public ToolsUpdateResponse update(String id, ToolsUpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).body();
    }
}
