/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum CampaignEndedReason {
    CAMPAIGN_SCHEDULED_ENDED_BY_USER("campaign.scheduled.ended-by-user"),

    CAMPAIGN_IN_PROGRESS_ENDED_BY_USER("campaign.in-progress.ended-by-user"),

    CAMPAIGN_ENDED_SUCCESS("campaign.ended.success");

    private final String value;

    CampaignEndedReason(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
