/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum CartesiaExperimentalControlsSpeed {
    SLOWEST("slowest"),

    SLOW("slow"),

    NORMAL("normal"),

    FAST("fast"),

    FASTEST("fastest");

    private final String value;

    CartesiaExperimentalControlsSpeed(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
