/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateComputerToolDto.Builder.class)
public final class CreateComputerToolDto {
    private final Optional<List<CreateComputerToolDtoMessagesItem>> messages;

    private final Optional<Server> server;

    private final double displayWidthPx;

    private final double displayHeightPx;

    private final Optional<Double> displayNumber;

    private final Optional<OpenAiFunction> function;

    private final Map<String, Object> additionalProperties;

    private CreateComputerToolDto(
            Optional<List<CreateComputerToolDtoMessagesItem>> messages,
            Optional<Server> server,
            double displayWidthPx,
            double displayHeightPx,
            Optional<Double> displayNumber,
            Optional<OpenAiFunction> function,
            Map<String, Object> additionalProperties) {
        this.messages = messages;
        this.server = server;
        this.displayWidthPx = displayWidthPx;
        this.displayHeightPx = displayHeightPx;
        this.displayNumber = displayNumber;
        this.function = function;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return These are the messages that will be spoken to the user as the tool is running.
     * <p>For some tools, this is auto-filled based on special fields like <code>tool.destinations</code>. For others like the function tool, these can be custom configured.</p>
     */
    @JsonProperty("messages")
    public Optional<List<CreateComputerToolDtoMessagesItem>> getMessages() {
        return messages;
    }

    /**
     * @return The sub type of tool.
     */
    @JsonProperty("subType")
    public String getSubType() {
        return "computer_20241022";
    }

    /**
     * @return This is the server where a <code>tool-calls</code> webhook will be sent.
     * <p>Notes:</p>
     * <ul>
     * <li>Webhook is sent to this server when a tool call is made.</li>
     * <li>Webhook contains the call, assistant, and phone number objects.</li>
     * <li>Webhook contains the variables set on the assistant.</li>
     * <li>Webhook is sent to the first available URL in this order: {{tool.server.url}}, {{assistant.server.url}}, {{phoneNumber.server.url}}, {{org.server.url}}.</li>
     * <li>Webhook expects a response with tool call result.</li>
     * </ul>
     */
    @JsonProperty("server")
    public Optional<Server> getServer() {
        return server;
    }

    /**
     * @return The name of the tool, fixed to 'computer'
     */
    @JsonProperty("name")
    public String getName() {
        return "computer";
    }

    /**
     * @return The display width in pixels
     */
    @JsonProperty("displayWidthPx")
    public double getDisplayWidthPx() {
        return displayWidthPx;
    }

    /**
     * @return The display height in pixels
     */
    @JsonProperty("displayHeightPx")
    public double getDisplayHeightPx() {
        return displayHeightPx;
    }

    /**
     * @return Optional display number
     */
    @JsonProperty("displayNumber")
    public Optional<Double> getDisplayNumber() {
        return displayNumber;
    }

    /**
     * @return This is the function definition of the tool.
     * <p>For <code>endCall</code>, <code>transferCall</code>, and <code>dtmf</code> tools, this is auto-filled based on tool-specific fields like <code>tool.destinations</code>. But, even in those cases, you can provide a custom function definition for advanced use cases.</p>
     * <p>An example of an advanced use case is if you want to customize the message that's spoken for <code>endCall</code> tool. You can specify a function where it returns an argument &quot;reason&quot;. Then, in <code>messages</code> array, you can have many &quot;request-complete&quot; messages. One of these messages will be triggered if the <code>messages[].conditions</code> matches the &quot;reason&quot; argument.</p>
     */
    @JsonProperty("function")
    public Optional<OpenAiFunction> getFunction() {
        return function;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateComputerToolDto && equalTo((CreateComputerToolDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateComputerToolDto other) {
        return messages.equals(other.messages)
                && server.equals(other.server)
                && displayWidthPx == other.displayWidthPx
                && displayHeightPx == other.displayHeightPx
                && displayNumber.equals(other.displayNumber)
                && function.equals(other.function);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.messages,
                this.server,
                this.displayWidthPx,
                this.displayHeightPx,
                this.displayNumber,
                this.function);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DisplayWidthPxStage builder() {
        return new Builder();
    }

    public interface DisplayWidthPxStage {
        /**
         * <p>The display width in pixels</p>
         */
        DisplayHeightPxStage displayWidthPx(double displayWidthPx);

        Builder from(CreateComputerToolDto other);
    }

    public interface DisplayHeightPxStage {
        /**
         * <p>The display height in pixels</p>
         */
        _FinalStage displayHeightPx(double displayHeightPx);
    }

    public interface _FinalStage {
        CreateComputerToolDto build();

        /**
         * <p>These are the messages that will be spoken to the user as the tool is running.</p>
         * <p>For some tools, this is auto-filled based on special fields like <code>tool.destinations</code>. For others like the function tool, these can be custom configured.</p>
         */
        _FinalStage messages(Optional<List<CreateComputerToolDtoMessagesItem>> messages);

        _FinalStage messages(List<CreateComputerToolDtoMessagesItem> messages);

        /**
         * <p>This is the server where a <code>tool-calls</code> webhook will be sent.</p>
         * <p>Notes:</p>
         * <ul>
         * <li>Webhook is sent to this server when a tool call is made.</li>
         * <li>Webhook contains the call, assistant, and phone number objects.</li>
         * <li>Webhook contains the variables set on the assistant.</li>
         * <li>Webhook is sent to the first available URL in this order: {{tool.server.url}}, {{assistant.server.url}}, {{phoneNumber.server.url}}, {{org.server.url}}.</li>
         * <li>Webhook expects a response with tool call result.</li>
         * </ul>
         */
        _FinalStage server(Optional<Server> server);

        _FinalStage server(Server server);

        /**
         * <p>Optional display number</p>
         */
        _FinalStage displayNumber(Optional<Double> displayNumber);

        _FinalStage displayNumber(Double displayNumber);

        /**
         * <p>This is the function definition of the tool.</p>
         * <p>For <code>endCall</code>, <code>transferCall</code>, and <code>dtmf</code> tools, this is auto-filled based on tool-specific fields like <code>tool.destinations</code>. But, even in those cases, you can provide a custom function definition for advanced use cases.</p>
         * <p>An example of an advanced use case is if you want to customize the message that's spoken for <code>endCall</code> tool. You can specify a function where it returns an argument &quot;reason&quot;. Then, in <code>messages</code> array, you can have many &quot;request-complete&quot; messages. One of these messages will be triggered if the <code>messages[].conditions</code> matches the &quot;reason&quot; argument.</p>
         */
        _FinalStage function(Optional<OpenAiFunction> function);

        _FinalStage function(OpenAiFunction function);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DisplayWidthPxStage, DisplayHeightPxStage, _FinalStage {
        private double displayWidthPx;

        private double displayHeightPx;

        private Optional<OpenAiFunction> function = Optional.empty();

        private Optional<Double> displayNumber = Optional.empty();

        private Optional<Server> server = Optional.empty();

        private Optional<List<CreateComputerToolDtoMessagesItem>> messages = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateComputerToolDto other) {
            messages(other.getMessages());
            server(other.getServer());
            displayWidthPx(other.getDisplayWidthPx());
            displayHeightPx(other.getDisplayHeightPx());
            displayNumber(other.getDisplayNumber());
            function(other.getFunction());
            return this;
        }

        /**
         * <p>The display width in pixels</p>
         * <p>The display width in pixels</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("displayWidthPx")
        public DisplayHeightPxStage displayWidthPx(double displayWidthPx) {
            this.displayWidthPx = displayWidthPx;
            return this;
        }

        /**
         * <p>The display height in pixels</p>
         * <p>The display height in pixels</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("displayHeightPx")
        public _FinalStage displayHeightPx(double displayHeightPx) {
            this.displayHeightPx = displayHeightPx;
            return this;
        }

        /**
         * <p>This is the function definition of the tool.</p>
         * <p>For <code>endCall</code>, <code>transferCall</code>, and <code>dtmf</code> tools, this is auto-filled based on tool-specific fields like <code>tool.destinations</code>. But, even in those cases, you can provide a custom function definition for advanced use cases.</p>
         * <p>An example of an advanced use case is if you want to customize the message that's spoken for <code>endCall</code> tool. You can specify a function where it returns an argument &quot;reason&quot;. Then, in <code>messages</code> array, you can have many &quot;request-complete&quot; messages. One of these messages will be triggered if the <code>messages[].conditions</code> matches the &quot;reason&quot; argument.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage function(OpenAiFunction function) {
            this.function = Optional.ofNullable(function);
            return this;
        }

        /**
         * <p>This is the function definition of the tool.</p>
         * <p>For <code>endCall</code>, <code>transferCall</code>, and <code>dtmf</code> tools, this is auto-filled based on tool-specific fields like <code>tool.destinations</code>. But, even in those cases, you can provide a custom function definition for advanced use cases.</p>
         * <p>An example of an advanced use case is if you want to customize the message that's spoken for <code>endCall</code> tool. You can specify a function where it returns an argument &quot;reason&quot;. Then, in <code>messages</code> array, you can have many &quot;request-complete&quot; messages. One of these messages will be triggered if the <code>messages[].conditions</code> matches the &quot;reason&quot; argument.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "function", nulls = Nulls.SKIP)
        public _FinalStage function(Optional<OpenAiFunction> function) {
            this.function = function;
            return this;
        }

        /**
         * <p>Optional display number</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage displayNumber(Double displayNumber) {
            this.displayNumber = Optional.ofNullable(displayNumber);
            return this;
        }

        /**
         * <p>Optional display number</p>
         */
        @java.lang.Override
        @JsonSetter(value = "displayNumber", nulls = Nulls.SKIP)
        public _FinalStage displayNumber(Optional<Double> displayNumber) {
            this.displayNumber = displayNumber;
            return this;
        }

        /**
         * <p>This is the server where a <code>tool-calls</code> webhook will be sent.</p>
         * <p>Notes:</p>
         * <ul>
         * <li>Webhook is sent to this server when a tool call is made.</li>
         * <li>Webhook contains the call, assistant, and phone number objects.</li>
         * <li>Webhook contains the variables set on the assistant.</li>
         * <li>Webhook is sent to the first available URL in this order: {{tool.server.url}}, {{assistant.server.url}}, {{phoneNumber.server.url}}, {{org.server.url}}.</li>
         * <li>Webhook expects a response with tool call result.</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage server(Server server) {
            this.server = Optional.ofNullable(server);
            return this;
        }

        /**
         * <p>This is the server where a <code>tool-calls</code> webhook will be sent.</p>
         * <p>Notes:</p>
         * <ul>
         * <li>Webhook is sent to this server when a tool call is made.</li>
         * <li>Webhook contains the call, assistant, and phone number objects.</li>
         * <li>Webhook contains the variables set on the assistant.</li>
         * <li>Webhook is sent to the first available URL in this order: {{tool.server.url}}, {{assistant.server.url}}, {{phoneNumber.server.url}}, {{org.server.url}}.</li>
         * <li>Webhook expects a response with tool call result.</li>
         * </ul>
         */
        @java.lang.Override
        @JsonSetter(value = "server", nulls = Nulls.SKIP)
        public _FinalStage server(Optional<Server> server) {
            this.server = server;
            return this;
        }

        /**
         * <p>These are the messages that will be spoken to the user as the tool is running.</p>
         * <p>For some tools, this is auto-filled based on special fields like <code>tool.destinations</code>. For others like the function tool, these can be custom configured.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage messages(List<CreateComputerToolDtoMessagesItem> messages) {
            this.messages = Optional.ofNullable(messages);
            return this;
        }

        /**
         * <p>These are the messages that will be spoken to the user as the tool is running.</p>
         * <p>For some tools, this is auto-filled based on special fields like <code>tool.destinations</code>. For others like the function tool, these can be custom configured.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "messages", nulls = Nulls.SKIP)
        public _FinalStage messages(Optional<List<CreateComputerToolDtoMessagesItem>> messages) {
            this.messages = messages;
            return this;
        }

        @java.lang.Override
        public CreateComputerToolDto build() {
            return new CreateComputerToolDto(
                    messages, server, displayWidthPx, displayHeightPx, displayNumber, function, additionalProperties);
        }
    }
}
