/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CredentialSessionResponse.Builder.class)
public final class CredentialSessionResponse {
    private final String sessionToken;

    private final Map<String, Object> additionalProperties;

    private CredentialSessionResponse(String sessionToken, Map<String, Object> additionalProperties) {
        this.sessionToken = sessionToken;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("sessionToken")
    public String getSessionToken() {
        return sessionToken;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CredentialSessionResponse && equalTo((CredentialSessionResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CredentialSessionResponse other) {
        return sessionToken.equals(other.sessionToken);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.sessionToken);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SessionTokenStage builder() {
        return new Builder();
    }

    public interface SessionTokenStage {
        _FinalStage sessionToken(@NotNull String sessionToken);

        Builder from(CredentialSessionResponse other);
    }

    public interface _FinalStage {
        CredentialSessionResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SessionTokenStage, _FinalStage {
        private String sessionToken;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CredentialSessionResponse other) {
            sessionToken(other.getSessionToken());
            return this;
        }

        @java.lang.Override
        @JsonSetter("sessionToken")
        public _FinalStage sessionToken(@NotNull String sessionToken) {
            this.sessionToken = Objects.requireNonNull(sessionToken, "sessionToken must not be null");
            return this;
        }

        @java.lang.Override
        public CredentialSessionResponse build() {
            return new CredentialSessionResponse(sessionToken, additionalProperties);
        }
    }
}
