/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomLlmCredential.Builder.class)
public final class CustomLlmCredential {
    private final String apiKey;

    private final Optional<OAuth2AuthenticationPlan> authenticationPlan;

    private final String id;

    private final String orgId;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Optional<Oauth2AuthenticationSession> authenticationSession;

    private final Optional<String> name;

    private final Map<String, Object> additionalProperties;

    private CustomLlmCredential(
            String apiKey,
            Optional<OAuth2AuthenticationPlan> authenticationPlan,
            String id,
            String orgId,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Optional<Oauth2AuthenticationSession> authenticationSession,
            Optional<String> name,
            Map<String, Object> additionalProperties) {
        this.apiKey = apiKey;
        this.authenticationPlan = authenticationPlan;
        this.id = id;
        this.orgId = orgId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.authenticationSession = authenticationSession;
        this.name = name;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("provider")
    public String getProvider() {
        return "custom-llm";
    }

    /**
     * @return This is not returned in the API.
     */
    @JsonProperty("apiKey")
    public String getApiKey() {
        return apiKey;
    }

    /**
     * @return This is the authentication plan. Currently supports OAuth2 RFC 6749. To use Bearer authentication, use apiKey
     */
    @JsonProperty("authenticationPlan")
    public Optional<OAuth2AuthenticationPlan> getAuthenticationPlan() {
        return authenticationPlan;
    }

    /**
     * @return This is the unique identifier for the credential.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return This is the unique identifier for the org that this credential belongs to.
     */
    @JsonProperty("orgId")
    public String getOrgId() {
        return orgId;
    }

    /**
     * @return This is the ISO 8601 date-time string of when the credential was created.
     */
    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return This is the ISO 8601 date-time string of when the assistant was last updated.
     */
    @JsonProperty("updatedAt")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * @return This is the authentication session for the credential. Available for credentials that have an authentication plan.
     */
    @JsonProperty("authenticationSession")
    public Optional<Oauth2AuthenticationSession> getAuthenticationSession() {
        return authenticationSession;
    }

    /**
     * @return This is the name of credential. This is just for your reference.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomLlmCredential && equalTo((CustomLlmCredential) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomLlmCredential other) {
        return apiKey.equals(other.apiKey)
                && authenticationPlan.equals(other.authenticationPlan)
                && id.equals(other.id)
                && orgId.equals(other.orgId)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt)
                && authenticationSession.equals(other.authenticationSession)
                && name.equals(other.name);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.apiKey,
                this.authenticationPlan,
                this.id,
                this.orgId,
                this.createdAt,
                this.updatedAt,
                this.authenticationSession,
                this.name);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ApiKeyStage builder() {
        return new Builder();
    }

    public interface ApiKeyStage {
        IdStage apiKey(@NotNull String apiKey);

        Builder from(CustomLlmCredential other);
    }

    public interface IdStage {
        OrgIdStage id(@NotNull String id);
    }

    public interface OrgIdStage {
        CreatedAtStage orgId(@NotNull String orgId);
    }

    public interface CreatedAtStage {
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        CustomLlmCredential build();

        _FinalStage authenticationPlan(Optional<OAuth2AuthenticationPlan> authenticationPlan);

        _FinalStage authenticationPlan(OAuth2AuthenticationPlan authenticationPlan);

        _FinalStage authenticationSession(Optional<Oauth2AuthenticationSession> authenticationSession);

        _FinalStage authenticationSession(Oauth2AuthenticationSession authenticationSession);

        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ApiKeyStage, IdStage, OrgIdStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
        private String apiKey;

        private String id;

        private String orgId;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private Optional<String> name = Optional.empty();

        private Optional<Oauth2AuthenticationSession> authenticationSession = Optional.empty();

        private Optional<OAuth2AuthenticationPlan> authenticationPlan = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomLlmCredential other) {
            apiKey(other.getApiKey());
            authenticationPlan(other.getAuthenticationPlan());
            id(other.getId());
            orgId(other.getOrgId());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            authenticationSession(other.getAuthenticationSession());
            name(other.getName());
            return this;
        }

        /**
         * <p>This is not returned in the API.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("apiKey")
        public IdStage apiKey(@NotNull String apiKey) {
            this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
            return this;
        }

        /**
         * <p>This is the unique identifier for the credential.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public OrgIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>This is the unique identifier for the org that this credential belongs to.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("orgId")
        public CreatedAtStage orgId(@NotNull String orgId) {
            this.orgId = Objects.requireNonNull(orgId, "orgId must not be null");
            return this;
        }

        /**
         * <p>This is the ISO 8601 date-time string of when the credential was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAt")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>This is the ISO 8601 date-time string of when the assistant was last updated.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>This is the name of credential. This is just for your reference.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        /**
         * <p>This is the authentication session for the credential. Available for credentials that have an authentication plan.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage authenticationSession(Oauth2AuthenticationSession authenticationSession) {
            this.authenticationSession = Optional.ofNullable(authenticationSession);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "authenticationSession", nulls = Nulls.SKIP)
        public _FinalStage authenticationSession(Optional<Oauth2AuthenticationSession> authenticationSession) {
            this.authenticationSession = authenticationSession;
            return this;
        }

        /**
         * <p>This is the authentication plan. Currently supports OAuth2 RFC 6749. To use Bearer authentication, use apiKey</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage authenticationPlan(OAuth2AuthenticationPlan authenticationPlan) {
            this.authenticationPlan = Optional.ofNullable(authenticationPlan);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "authenticationPlan", nulls = Nulls.SKIP)
        public _FinalStage authenticationPlan(Optional<OAuth2AuthenticationPlan> authenticationPlan) {
            this.authenticationPlan = authenticationPlan;
            return this;
        }

        @java.lang.Override
        public CustomLlmCredential build() {
            return new CustomLlmCredential(
                    apiKey,
                    authenticationPlan,
                    id,
                    orgId,
                    createdAt,
                    updatedAt,
                    authenticationSession,
                    name,
                    additionalProperties);
        }
    }
}
