/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeveloperMessage.Builder.class)
public final class DeveloperMessage {
    private final String content;

    private final Optional<String> name;

    private final Map<String, Object> additionalProperties;

    private DeveloperMessage(String content, Optional<String> name, Map<String, Object> additionalProperties) {
        this.content = content;
        this.name = name;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return This is the role of the message author
     */
    @JsonProperty("role")
    public String getRole() {
        return "developer";
    }

    /**
     * @return This is the content of the developer message
     */
    @JsonProperty("content")
    public String getContent() {
        return content;
    }

    /**
     * @return This is an optional name for the participant
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeveloperMessage && equalTo((DeveloperMessage) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeveloperMessage other) {
        return content.equals(other.content) && name.equals(other.name);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.content, this.name);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ContentStage builder() {
        return new Builder();
    }

    public interface ContentStage {
        /**
         * <p>This is the content of the developer message</p>
         */
        _FinalStage content(@NotNull String content);

        Builder from(DeveloperMessage other);
    }

    public interface _FinalStage {
        DeveloperMessage build();

        /**
         * <p>This is an optional name for the participant</p>
         */
        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ContentStage, _FinalStage {
        private String content;

        private Optional<String> name = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DeveloperMessage other) {
            content(other.getContent());
            name(other.getName());
            return this;
        }

        /**
         * <p>This is the content of the developer message</p>
         * <p>This is the content of the developer message</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("content")
        public _FinalStage content(@NotNull String content) {
            this.content = Objects.requireNonNull(content, "content must not be null");
            return this;
        }

        /**
         * <p>This is an optional name for the participant</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>This is an optional name for the participant</p>
         */
        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        public DeveloperMessage build() {
            return new DeveloperMessage(content, name, additionalProperties);
        }
    }
}
