/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FallbackNeetsVoice.Builder.class)
public final class FallbackNeetsVoice {
    private final Optional<Object> voiceId;

    private final Map<String, Object> additionalProperties;

    private FallbackNeetsVoice(Optional<Object> voiceId, Map<String, Object> additionalProperties) {
        this.voiceId = voiceId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("voiceId")
    public Optional<Object> getVoiceId() {
        return voiceId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FallbackNeetsVoice && equalTo((FallbackNeetsVoice) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FallbackNeetsVoice other) {
        return voiceId.equals(other.voiceId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.voiceId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Object> voiceId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(FallbackNeetsVoice other) {
            voiceId(other.getVoiceId());
            return this;
        }

        @JsonSetter(value = "voiceId", nulls = Nulls.SKIP)
        public Builder voiceId(Optional<Object> voiceId) {
            this.voiceId = voiceId;
            return this;
        }

        public Builder voiceId(Object voiceId) {
            this.voiceId = Optional.ofNullable(voiceId);
            return this;
        }

        public FallbackNeetsVoice build() {
            return new FallbackNeetsVoice(voiceId, additionalProperties);
        }
    }
}
