/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FallbackCartesiaVoice.Builder.class)
public final class FallbackCartesiaVoice {
    private final String voiceId;

    private final Optional<FallbackCartesiaVoiceModel> model;

    private final Optional<FallbackCartesiaVoiceLanguage> language;

    private final Optional<CartesiaExperimentalControls> experimentalControls;

    private final Optional<ChunkPlan> chunkPlan;

    private final Map<String, Object> additionalProperties;

    private FallbackCartesiaVoice(
            String voiceId,
            Optional<FallbackCartesiaVoiceModel> model,
            Optional<FallbackCartesiaVoiceLanguage> language,
            Optional<CartesiaExperimentalControls> experimentalControls,
            Optional<ChunkPlan> chunkPlan,
            Map<String, Object> additionalProperties) {
        this.voiceId = voiceId;
        this.model = model;
        this.language = language;
        this.experimentalControls = experimentalControls;
        this.chunkPlan = chunkPlan;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The ID of the particular voice you want to use.
     */
    @JsonProperty("voiceId")
    public String getVoiceId() {
        return voiceId;
    }

    /**
     * @return This is the model that will be used. This is optional and will default to the correct model for the voiceId.
     */
    @JsonProperty("model")
    public Optional<FallbackCartesiaVoiceModel> getModel() {
        return model;
    }

    /**
     * @return This is the language that will be used. This is optional and will default to the correct language for the voiceId.
     */
    @JsonProperty("language")
    public Optional<FallbackCartesiaVoiceLanguage> getLanguage() {
        return language;
    }

    /**
     * @return Experimental controls for Cartesia voice generation
     */
    @JsonProperty("experimentalControls")
    public Optional<CartesiaExperimentalControls> getExperimentalControls() {
        return experimentalControls;
    }

    /**
     * @return This is the plan for chunking the model output before it is sent to the voice provider.
     */
    @JsonProperty("chunkPlan")
    public Optional<ChunkPlan> getChunkPlan() {
        return chunkPlan;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FallbackCartesiaVoice && equalTo((FallbackCartesiaVoice) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FallbackCartesiaVoice other) {
        return voiceId.equals(other.voiceId)
                && model.equals(other.model)
                && language.equals(other.language)
                && experimentalControls.equals(other.experimentalControls)
                && chunkPlan.equals(other.chunkPlan);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.voiceId, this.model, this.language, this.experimentalControls, this.chunkPlan);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static VoiceIdStage builder() {
        return new Builder();
    }

    public interface VoiceIdStage {
        _FinalStage voiceId(@NotNull String voiceId);

        Builder from(FallbackCartesiaVoice other);
    }

    public interface _FinalStage {
        FallbackCartesiaVoice build();

        _FinalStage model(Optional<FallbackCartesiaVoiceModel> model);

        _FinalStage model(FallbackCartesiaVoiceModel model);

        _FinalStage language(Optional<FallbackCartesiaVoiceLanguage> language);

        _FinalStage language(FallbackCartesiaVoiceLanguage language);

        _FinalStage experimentalControls(Optional<CartesiaExperimentalControls> experimentalControls);

        _FinalStage experimentalControls(CartesiaExperimentalControls experimentalControls);

        _FinalStage chunkPlan(Optional<ChunkPlan> chunkPlan);

        _FinalStage chunkPlan(ChunkPlan chunkPlan);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements VoiceIdStage, _FinalStage {
        private String voiceId;

        private Optional<ChunkPlan> chunkPlan = Optional.empty();

        private Optional<CartesiaExperimentalControls> experimentalControls = Optional.empty();

        private Optional<FallbackCartesiaVoiceLanguage> language = Optional.empty();

        private Optional<FallbackCartesiaVoiceModel> model = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FallbackCartesiaVoice other) {
            voiceId(other.getVoiceId());
            model(other.getModel());
            language(other.getLanguage());
            experimentalControls(other.getExperimentalControls());
            chunkPlan(other.getChunkPlan());
            return this;
        }

        /**
         * <p>The ID of the particular voice you want to use.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("voiceId")
        public _FinalStage voiceId(@NotNull String voiceId) {
            this.voiceId = Objects.requireNonNull(voiceId, "voiceId must not be null");
            return this;
        }

        /**
         * <p>This is the plan for chunking the model output before it is sent to the voice provider.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage chunkPlan(ChunkPlan chunkPlan) {
            this.chunkPlan = Optional.ofNullable(chunkPlan);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "chunkPlan", nulls = Nulls.SKIP)
        public _FinalStage chunkPlan(Optional<ChunkPlan> chunkPlan) {
            this.chunkPlan = chunkPlan;
            return this;
        }

        /**
         * <p>Experimental controls for Cartesia voice generation</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage experimentalControls(CartesiaExperimentalControls experimentalControls) {
            this.experimentalControls = Optional.ofNullable(experimentalControls);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "experimentalControls", nulls = Nulls.SKIP)
        public _FinalStage experimentalControls(Optional<CartesiaExperimentalControls> experimentalControls) {
            this.experimentalControls = experimentalControls;
            return this;
        }

        /**
         * <p>This is the language that will be used. This is optional and will default to the correct language for the voiceId.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage language(FallbackCartesiaVoiceLanguage language) {
            this.language = Optional.ofNullable(language);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "language", nulls = Nulls.SKIP)
        public _FinalStage language(Optional<FallbackCartesiaVoiceLanguage> language) {
            this.language = language;
            return this;
        }

        /**
         * <p>This is the model that will be used. This is optional and will default to the correct model for the voiceId.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage model(FallbackCartesiaVoiceModel model) {
            this.model = Optional.ofNullable(model);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "model", nulls = Nulls.SKIP)
        public _FinalStage model(Optional<FallbackCartesiaVoiceModel> model) {
            this.model = model;
            return this;
        }

        @java.lang.Override
        public FallbackCartesiaVoice build() {
            return new FallbackCartesiaVoice(
                    voiceId, model, language, experimentalControls, chunkPlan, additionalProperties);
        }
    }
}
