/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum GladiaTranscriberModel {
    FAST("fast"),

    ACCURATE("accurate"),

    SOLARIA_1("solaria-1");

    private final String value;

    GladiaTranscriberModel(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
