/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum HmacAuthenticationPlanAlgorithm {
    SHA_256("sha256"),

    SHA_512("sha512"),

    SHA_1("sha1");

    private final String value;

    HmacAuthenticationPlanAlgorithm(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
