/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum LogResource {
    ASSISTANT("assistant"),

    PHONE_NUMBER("phone-number"),

    TOOL("tool"),

    SQUAD("squad"),

    CALL("call"),

    FILE("file"),

    METRIC("metric"),

    LOG("log");

    private final String value;

    LogResource(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
