/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum OpenAiVoiceModel {
    TTS_1("tts-1"),

    TTS_1_HD("tts-1-hd"),

    GPT_4_O_MINI_TTS("gpt-4o-mini-tts");

    private final String value;

    OpenAiVoiceModel(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
