/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SayHook.Builder.class)
public final class SayHook {
    private final Optional<Map<String, Object>> metadata;

    private final Optional<String> exact;

    private final Optional<String> prompt;

    private final Map<String, Object> additionalProperties;

    private SayHook(
            Optional<Map<String, Object>> metadata,
            Optional<String> exact,
            Optional<String> prompt,
            Map<String, Object> additionalProperties) {
        this.metadata = metadata;
        this.exact = exact;
        this.prompt = prompt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public String getType() {
        return "say";
    }

    /**
     * @return This is for metadata you want to store on the task.
     */
    @JsonProperty("metadata")
    public Optional<Map<String, Object>> getMetadata() {
        return metadata;
    }

    @JsonProperty("exact")
    public Optional<String> getExact() {
        return exact;
    }

    @JsonProperty("prompt")
    public Optional<String> getPrompt() {
        return prompt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SayHook && equalTo((SayHook) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SayHook other) {
        return metadata.equals(other.metadata) && exact.equals(other.exact) && prompt.equals(other.prompt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.metadata, this.exact, this.prompt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Map<String, Object>> metadata = Optional.empty();

        private Optional<String> exact = Optional.empty();

        private Optional<String> prompt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SayHook other) {
            metadata(other.getMetadata());
            exact(other.getExact());
            prompt(other.getPrompt());
            return this;
        }

        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public Builder metadata(Optional<Map<String, Object>> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder metadata(Map<String, Object> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        @JsonSetter(value = "exact", nulls = Nulls.SKIP)
        public Builder exact(Optional<String> exact) {
            this.exact = exact;
            return this;
        }

        public Builder exact(String exact) {
            this.exact = Optional.ofNullable(exact);
            return this;
        }

        @JsonSetter(value = "prompt", nulls = Nulls.SKIP)
        public Builder prompt(Optional<String> prompt) {
            this.prompt = prompt;
            return this;
        }

        public Builder prompt(String prompt) {
            this.prompt = Optional.ofNullable(prompt);
            return this;
        }

        public SayHook build() {
            return new SayHook(metadata, exact, prompt, additionalProperties);
        }
    }
}
