/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ServerMessageConversationUpdate.Builder.class)
public final class ServerMessageConversationUpdate {
    private final Optional<ServerMessageConversationUpdatePhoneNumber> phoneNumber;

    private final Optional<List<ServerMessageConversationUpdateMessagesItem>> messages;

    private final List<OpenAiMessage> messagesOpenAiFormatted;

    private final Optional<String> timestamp;

    private final Optional<Artifact> artifact;

    private final Optional<CreateAssistantDto> assistant;

    private final Optional<CreateCustomerDto> customer;

    private final Optional<Call> call;

    private final Map<String, Object> additionalProperties;

    private ServerMessageConversationUpdate(
            Optional<ServerMessageConversationUpdatePhoneNumber> phoneNumber,
            Optional<List<ServerMessageConversationUpdateMessagesItem>> messages,
            List<OpenAiMessage> messagesOpenAiFormatted,
            Optional<String> timestamp,
            Optional<Artifact> artifact,
            Optional<CreateAssistantDto> assistant,
            Optional<CreateCustomerDto> customer,
            Optional<Call> call,
            Map<String, Object> additionalProperties) {
        this.phoneNumber = phoneNumber;
        this.messages = messages;
        this.messagesOpenAiFormatted = messagesOpenAiFormatted;
        this.timestamp = timestamp;
        this.artifact = artifact;
        this.assistant = assistant;
        this.customer = customer;
        this.call = call;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return This is the phone number associated with the call.
     * <p>This matches one of the following:</p>
     * <ul>
     * <li><code>call.phoneNumber</code>,</li>
     * <li><code>call.phoneNumberId</code>.</li>
     * </ul>
     */
    @JsonProperty("phoneNumber")
    public Optional<ServerMessageConversationUpdatePhoneNumber> getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @return This is the most up-to-date conversation history at the time the message is sent.
     */
    @JsonProperty("messages")
    public Optional<List<ServerMessageConversationUpdateMessagesItem>> getMessages() {
        return messages;
    }

    /**
     * @return This is the most up-to-date conversation history at the time the message is sent, formatted for OpenAI.
     */
    @JsonProperty("messagesOpenAIFormatted")
    public List<OpenAiMessage> getMessagesOpenAiFormatted() {
        return messagesOpenAiFormatted;
    }

    /**
     * @return This is the ISO-8601 formatted timestamp of when the message was sent.
     */
    @JsonProperty("timestamp")
    public Optional<String> getTimestamp() {
        return timestamp;
    }

    /**
     * @return This is a live version of the <code>call.artifact</code>.
     * <p>This matches what is stored on <code>call.artifact</code> after the call.</p>
     */
    @JsonProperty("artifact")
    public Optional<Artifact> getArtifact() {
        return artifact;
    }

    /**
     * @return This is the assistant that is currently active. This is provided for convenience.
     * <p>This matches one of the following:</p>
     * <ul>
     * <li><code>call.assistant</code>,</li>
     * <li><code>call.assistantId</code>,</li>
     * <li><code>call.squad[n].assistant</code>,</li>
     * <li><code>call.squad[n].assistantId</code>,</li>
     * <li><code>call.squadId-&gt;[n].assistant</code>,</li>
     * <li><code>call.squadId-&gt;[n].assistantId</code>.</li>
     * </ul>
     */
    @JsonProperty("assistant")
    public Optional<CreateAssistantDto> getAssistant() {
        return assistant;
    }

    /**
     * @return This is the customer associated with the call.
     * <p>This matches one of the following:</p>
     * <ul>
     * <li><code>call.customer</code>,</li>
     * <li><code>call.customerId</code>.</li>
     * </ul>
     */
    @JsonProperty("customer")
    public Optional<CreateCustomerDto> getCustomer() {
        return customer;
    }

    /**
     * @return This is the call object.
     * <p>This matches what was returned in POST /call.</p>
     * <p>Note: This might get stale during the call. To get the latest call object, especially after the call is ended, use GET /call/:id.</p>
     */
    @JsonProperty("call")
    public Optional<Call> getCall() {
        return call;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ServerMessageConversationUpdate && equalTo((ServerMessageConversationUpdate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ServerMessageConversationUpdate other) {
        return phoneNumber.equals(other.phoneNumber)
                && messages.equals(other.messages)
                && messagesOpenAiFormatted.equals(other.messagesOpenAiFormatted)
                && timestamp.equals(other.timestamp)
                && artifact.equals(other.artifact)
                && assistant.equals(other.assistant)
                && customer.equals(other.customer)
                && call.equals(other.call);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.phoneNumber,
                this.messages,
                this.messagesOpenAiFormatted,
                this.timestamp,
                this.artifact,
                this.assistant,
                this.customer,
                this.call);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ServerMessageConversationUpdatePhoneNumber> phoneNumber = Optional.empty();

        private Optional<List<ServerMessageConversationUpdateMessagesItem>> messages = Optional.empty();

        private List<OpenAiMessage> messagesOpenAiFormatted = new ArrayList<>();

        private Optional<String> timestamp = Optional.empty();

        private Optional<Artifact> artifact = Optional.empty();

        private Optional<CreateAssistantDto> assistant = Optional.empty();

        private Optional<CreateCustomerDto> customer = Optional.empty();

        private Optional<Call> call = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ServerMessageConversationUpdate other) {
            phoneNumber(other.getPhoneNumber());
            messages(other.getMessages());
            messagesOpenAiFormatted(other.getMessagesOpenAiFormatted());
            timestamp(other.getTimestamp());
            artifact(other.getArtifact());
            assistant(other.getAssistant());
            customer(other.getCustomer());
            call(other.getCall());
            return this;
        }

        @JsonSetter(value = "phoneNumber", nulls = Nulls.SKIP)
        public Builder phoneNumber(Optional<ServerMessageConversationUpdatePhoneNumber> phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        public Builder phoneNumber(ServerMessageConversationUpdatePhoneNumber phoneNumber) {
            this.phoneNumber = Optional.ofNullable(phoneNumber);
            return this;
        }

        @JsonSetter(value = "messages", nulls = Nulls.SKIP)
        public Builder messages(Optional<List<ServerMessageConversationUpdateMessagesItem>> messages) {
            this.messages = messages;
            return this;
        }

        public Builder messages(List<ServerMessageConversationUpdateMessagesItem> messages) {
            this.messages = Optional.ofNullable(messages);
            return this;
        }

        @JsonSetter(value = "messagesOpenAIFormatted", nulls = Nulls.SKIP)
        public Builder messagesOpenAiFormatted(List<OpenAiMessage> messagesOpenAiFormatted) {
            this.messagesOpenAiFormatted.clear();
            this.messagesOpenAiFormatted.addAll(messagesOpenAiFormatted);
            return this;
        }

        public Builder addMessagesOpenAiFormatted(OpenAiMessage messagesOpenAiFormatted) {
            this.messagesOpenAiFormatted.add(messagesOpenAiFormatted);
            return this;
        }

        public Builder addAllMessagesOpenAiFormatted(List<OpenAiMessage> messagesOpenAiFormatted) {
            this.messagesOpenAiFormatted.addAll(messagesOpenAiFormatted);
            return this;
        }

        @JsonSetter(value = "timestamp", nulls = Nulls.SKIP)
        public Builder timestamp(Optional<String> timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        public Builder timestamp(String timestamp) {
            this.timestamp = Optional.ofNullable(timestamp);
            return this;
        }

        @JsonSetter(value = "artifact", nulls = Nulls.SKIP)
        public Builder artifact(Optional<Artifact> artifact) {
            this.artifact = artifact;
            return this;
        }

        public Builder artifact(Artifact artifact) {
            this.artifact = Optional.ofNullable(artifact);
            return this;
        }

        @JsonSetter(value = "assistant", nulls = Nulls.SKIP)
        public Builder assistant(Optional<CreateAssistantDto> assistant) {
            this.assistant = assistant;
            return this;
        }

        public Builder assistant(CreateAssistantDto assistant) {
            this.assistant = Optional.ofNullable(assistant);
            return this;
        }

        @JsonSetter(value = "customer", nulls = Nulls.SKIP)
        public Builder customer(Optional<CreateCustomerDto> customer) {
            this.customer = customer;
            return this;
        }

        public Builder customer(CreateCustomerDto customer) {
            this.customer = Optional.ofNullable(customer);
            return this;
        }

        @JsonSetter(value = "call", nulls = Nulls.SKIP)
        public Builder call(Optional<Call> call) {
            this.call = call;
            return this;
        }

        public Builder call(Call call) {
            this.call = Optional.ofNullable(call);
            return this;
        }

        public ServerMessageConversationUpdate build() {
            return new ServerMessageConversationUpdate(
                    phoneNumber,
                    messages,
                    messagesOpenAiFormatted,
                    timestamp,
                    artifact,
                    assistant,
                    customer,
                    call,
                    additionalProperties);
        }
    }
}
