/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SpeechmaticsTranscriberLanguage {
    AUTO("auto"),

    AR("ar"),

    BA("ba"),

    EU("eu"),

    BE("be"),

    BN("bn"),

    BG("bg"),

    YUE("yue"),

    CA("ca"),

    HR("hr"),

    CS("cs"),

    DA("da"),

    NL("nl"),

    EN("en"),

    EO("eo"),

    ET("et"),

    FI("fi"),

    FR("fr"),

    GL("gl"),

    DE("de"),

    EL("el"),

    HE("he"),

    HI("hi"),

    HU("hu"),

    ID("id"),

    IA("ia"),

    GA("ga"),

    IT("it"),

    JA("ja"),

    KO("ko"),

    LV("lv"),

    LT("lt"),

    MS("ms"),

    MT("mt"),

    CMN("cmn"),

    MR("mr"),

    MN("mn"),

    NO("no"),

    FA("fa"),

    PL("pl"),

    PT("pt"),

    RO("ro"),

    RU("ru"),

    SK("sk"),

    SL("sl"),

    ES("es"),

    SW("sw"),

    SV("sv"),

    TA("ta"),

    TH("th"),

    TR("tr"),

    UK("uk"),

    UR("ur"),

    UG("ug"),

    VI("vi"),

    CY("cy");

    private final String value;

    SpeechmaticsTranscriberLanguage(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
