/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vapi.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vapi.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VariableExtractionPlan.Builder.class)
public final class VariableExtractionPlan {
    private final List<VariableExtractionSchema> output;

    private final Map<String, Object> additionalProperties;

    private VariableExtractionPlan(List<VariableExtractionSchema> output, Map<String, Object> additionalProperties) {
        this.output = output;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("output")
    public List<VariableExtractionSchema> getOutput() {
        return output;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VariableExtractionPlan && equalTo((VariableExtractionPlan) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VariableExtractionPlan other) {
        return output.equals(other.output);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.output);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<VariableExtractionSchema> output = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(VariableExtractionPlan other) {
            output(other.getOutput());
            return this;
        }

        @JsonSetter(value = "output", nulls = Nulls.SKIP)
        public Builder output(List<VariableExtractionSchema> output) {
            this.output.clear();
            this.output.addAll(output);
            return this;
        }

        public Builder addOutput(VariableExtractionSchema output) {
            this.output.add(output);
            return this;
        }

        public Builder addAllOutput(List<VariableExtractionSchema> output) {
            this.output.addAll(output);
            return this;
        }

        public VariableExtractionPlan build() {
            return new VariableExtractionPlan(output, additionalProperties);
        }
    }
}
